# 配置服务端口信息
server:
  port: 8080
#  配置数据源
spring:
  datasource:
    url: jdbc:mysql://cdb-ju9034j0.cd.tencentcdb.com:10051/test_schema
    username: root
    password: 54tanghui
#jpa相关的配置
  jpa:
#    自动创建、更新、验证数据库结构
    hibernate:
      ddl-auto: update
#    设置数据库引擎为InnoDB
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    打印sql语句，方便调试
    show-sql: true